build_config: &build_config
  CACHE_VERSION: v2
  NODE_VERSION: "18.20.3"
  JDK_ROOT: "https://cdn.azul.com/zulu/bin"
  JAVA_VERSION: "zulu8.78.0.19-ca-jdk8.0.412"

version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:

  build_linux:

    environment:
      <<: *build_config

    docker:
      - image: cimg/node:${NODE_VERSION}

    steps:
      - checkout
      - restore_cache:
          key: cache-${CACHE_VERSION}-linux-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Validate JDK/JRE and install if necessary
          command: |
              [[ ! -d build_resources/${JAVA_VERSION}-linux_x64 ]] && {
                [[ -d build_resources/jre/linux-x64 ]] && { rm -rf build_resources/jre/linux-x64; }
                wget -nc ${JDK_ROOT}/${JAVA_VERSION}-linux_x64.tar.gz
                tar xf ${JAVA_VERSION}-linux_x64.tar.gz -C build_resources
                cp -R build_resources/${JAVA_VERSION}-linux_x64/jre build_resources/jre/linux-x64
                rm -f ${JAVA_VERSION}-linux_x64.tar.gz
              }
      - run:
          name: Install and build node dependencies
          command: yarn install
      - save_cache:
          key: cache-${CACHE_VERSION}-linux-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - build_resources/jre
      - run:
          name: Build Linux 64-bit executable and installer
          command: |
              export JAVA_HOME="$(pwd)/build_resources/${JAVA_VERSION}-linux_x64"
              yarn dist-linux-x64
      - run:
          name: Copy build artifacts to artifacts folder
          command: |
            [[ ! -d artifacts ]] && { mkdir -p artifacts; }
            find dist -mindepth 1 -maxdepth 1 -type f -print0 | xargs --null -I {} cp {} artifacts
      - run:
          name: Upload artifacts to Bitbucket downloads page when the build is on the master branch
          command: |
            [[ ${CIRCLE_BRANCH} == "master" ]] && {
                echo "Found build on master branch, pushing artifacts to: https://api.bitbucket.org/2.0/repositories/${BB_REPO_SLUG}/${TARGET}/downloads"
                echo ""
                echo "Artifacts:"
                for ARTIFACT in $(find artifacts -type f ! -name "latest.yml" ! -name "alpha.yml" ! -name "beta.yml" ! -name "*.exe*"); do
                    echo " * ${ARTIFACT}"
                done
                http --auth "${BB_REPO_OWNER}:${BB_REPO_TOKEN}" --check-status --form POST "https://api.bitbucket.org/2.0/repositories/${BB_REPO_SLUG}/${TARGET}/downloads" $(for ARTIFACT in $(find artifacts -type f ! -name "latest.yml" ! -name "alpha.yml" ! -name "beta.yml" ! -name "*.exe*"); do echo files@${ARTIFACT}; done)
            } || {
                echo "Build on ${CIRCLE_BRANCH} branch, no artifacts pushed to application downloads page"
            }
      - store_artifacts:
          path: artifacts

  build_mac:

    environment:
      <<: *build_config

    macos:
      xcode: 15.3.0
      resource_class: macos.m1.medium.gen1

    steps:
      - run:
          name: Install httpie
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew install httpie
      - run:
          name: Install NVM and node
          command: |
            set +e
            http --body https://raw.githubusercontent.com/creationix/nvm/v${NVM_VERSION}/install.sh | bash
            echo "export NVM_DIR=\""'${HOME}'"/.nvm\"" >> ~/.bash_profile
            echo "[ -s \""'${NVM_DIR}'"/nvm.sh\" ] && source \""'${NVM_DIR}'"/nvm.sh\"" >> ~/.bash_profile
            source ${HOME}/.nvm/nvm.sh
            nvm install v${NODE_VERSION}
            nvm alias default v${NODE_VERSION}
            nvm use default
      - checkout
      - restore_cache:
          key: cache-${CACHE_VERSION}-mac-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Download and expand JREs for Mac
          command: |
            for BUILD_ARCH in arm64 x64; do
              [[ -d build_resources/jre/mac-${BUILD_ARCH} ]] && {
                [[ $(find build_resources/jre/mac-${BUILD_ARCH} -mindepth 1 -maxdepth 1 -type d -name bin | wc -l | tr -d ' ') == 0 ||
                   ! -f build_resources/jre/mac-${BUILD_ARCH}/bin/java ||
                   $(build_resources/jre/mac-${BUILD_ARCH}/bin/java -version 2>&1 | grep Server | wc -l | tr -d ' ') == 0 ]] && {
                    echo "The JRE at build_resources/jre/mac-${BUILD_ARCH} is displeasing to me, deleting"
                    rm -rf build_resources/jre/mac-${BUILD_ARCH}
                 }
              }
              [[ ! -d build_resources/jre/mac-${BUILD_ARCH} ]] && {
                  TARGET_ARCH="${BUILD_ARCH}"
                  [[ "${BUILD_ARCH}" == "arm64" ]] && { TARGET_ARCH="aarch64"; }
                  JAVA_TARGET="${JAVA_VERSION}-macosx_${TARGET_ARCH}"
                  echo "No JDK found for ${BUILD_ARCH}, downloading ${JDK_ROOT}/${JAVA_TARGET}.tar.gz"
                  mkdir -p build_resources/jre
                  http --download --output=build_resources/jre/${JAVA_TARGET}.tar.gz ${JDK_ROOT}/${JAVA_TARGET}.tar.gz
                  tar xf build_resources/jre/${JAVA_TARGET}.tar.gz --directory build_resources/jre
                  cp -R build_resources/jre/${JAVA_TARGET}/zulu-8.jdk/Contents/Home/jre build_resources/jre/mac-${BUILD_ARCH}
                  echo "JRE installed, using version: $(build_resources/jre/mac-${BUILD_ARCH}/bin/java -version 2>&1 | grep Server)"
              } || {
                  echo "Existing JRE found, using version: $(build_resources/jre/mac-${BUILD_ARCH}/bin/java -version 2>&1 | grep Server)"
              }
              # Last, make sure there are no read-only files! These cause the update process to fail.
              find build_resources/jre/mac-${BUILD_ARCH} -type f -perm +444 ! -perm +222 -exec chmod +w '{}' \;
            done
      - run:
          name: Download and install JDK
          command: |
            [[ ! -d /Library/Java/JavaVirtualMachines/zulu-8.jdk ]] && {
                JAVA_TARGET="${JAVA_VERSION}-macosx_x64"
                [[ ! -d build_resources/jre/${JAVA_TARGET} ]] && {
                  http --download --output=build_resources/jre/${JAVA_TARGET}.tar.gz ${JDK_ROOT}/${JAVA_TARGET}.tar.gz
                  tar xf build_resources/jre/${JAVA_TARGET}.tar.gz --directory build_resources/jre
                }
                sudo cp -R build_resources/jre/${JAVA_TARGET}/zulu-8.jdk /Library/Java/JavaVirtualMachines
                echo "JDK ${JAVA_TARGET} installed, using version: $(/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java -version 2>&1 | grep Server)"
            } || {
                echo "Existing JDK found, using version: $(/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/bin/java -version 2>&1 | grep Server)"
            }
      - run:
          name: Copy installed JDK to application folder
          command: |
            [[ ! -f /Applications/XNAT-Desktop-Client.app/Contents/Resources/jre/lib/jli/libjli.dylib ]] && {
              [[ -d /Applications/XNAT-Desktop-Client.app ]] && { rm -rf /Applications/XNAT-Desktop-Client.app; }
              cp -R /Library/Java/JavaVirtualMachines/zulu-8.jdk /Applications/XNAT-Desktop-Client.app
              cp -R /Applications/XNAT-Desktop-Client.app/Contents/Home /Applications/XNAT-Desktop-Client.app/Contents/Resources
            }
            [[ -f /Applications/XNAT-Desktop-Client.app/Contents/Resources/jre/lib/jli/libjli.dylib ]] || { echo "Tried to install libjli.dylib but something went wrong"; }
      - run:
          name: Install and build node dependencies
          command: |
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
            yarn install
      - save_cache:
          key: cache-${CACHE_VERSION}-mac-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - build_resources/jre/mac-arm64
            - build_resources/jre/mac-x64
            - /Applications/XNAT-Desktop-Client.app
            - /Library/Java/JavaVirtualMachines/zulu-8.jdk
      - run:
          name: Build Mac executable and installer
          command: |
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
            yarn dist-mac
      - run:
          name: Copy build artifacts to artifacts folder
          command: |
            [[ ! -d artifacts ]] && { mkdir -p artifacts; }
            find dist -mindepth 1 -maxdepth 1 -type f | xargs -I {} cp {} artifacts
      - run:
          name: Upload artifacts to Bitbucket downloads page when the build is on the master branch
          command: |
            [[ ${CIRCLE_BRANCH} == "master" ]] && {
                echo "Found build on master branch, pushing artifacts to: https://api.bitbucket.org/2.0/repositories/${BB_REPO_SLUG}/${TARGET}/downloads"
                echo ""
                echo "Artifacts:"
                for ARTIFACT in $(find artifacts -type f); do
                    echo " * ${ARTIFACT}"
                done
                http --auth "${BB_REPO_OWNER}:${BB_REPO_TOKEN}" --check-status --form POST "https://api.bitbucket.org/2.0/repositories/${BB_REPO_SLUG}/${TARGET}/downloads" $(for ARTIFACT in $(find artifacts -type f); do echo files@${ARTIFACT}; done)
            } || {
                echo "Build on ${CIRCLE_BRANCH} branch, no artifacts pushed to application downloads page"
            }
      - store_artifacts:
          path: artifacts

  build_win:

    environment:
      <<: *build_config

    executor: win/server-2019
    steps:
      - run: Write-Host "Hello, Windows"
      - run: pwd
      - run: nvm install 18.20.4
      - run: nvm use 18.20.4
      - run: npm install --global yarn
      - run: yarn --version

workflows:

  version: 2

  build_all:

    jobs:
      - build_linux:
          context: dxm
      - build_mac:
          context: dxm
      - build_win:
          context: dxm
